// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5iIySitQa1oU6Pt5Uat5n1vjXncwfswo',
    appId: '1:1005902372898:web:2279a72defbf8dee10ea7b',
    messagingSenderId: '1005902372898',
    projectId: 'blooddonation-28b11',
    authDomain: 'blooddonation-28b11.firebaseapp.com',
    storageBucket: 'blooddonation-28b11.firebasestorage.app',
    measurementId: 'G-C335G215HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3mxQBiJWyfrfhJDYjo8sjjmXxQ2SR5_E',
    appId: '1:1005902372898:android:13366f3bd25ba6b010ea7b',
    messagingSenderId: '1005902372898',
    projectId: 'blooddonation-28b11',
    storageBucket: 'blooddonation-28b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_wrY8swt1V2a38iM7qU7Z_Et0C1pIpP0',
    appId: '1:1005902372898:ios:47b057f031e7b73a10ea7b',
    messagingSenderId: '1005902372898',
    projectId: 'blooddonation-28b11',
    storageBucket: 'blooddonation-28b11.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );
}
